holograms:
  piggy-bank-name: "Het spek varken"
  latest-death: "De laatste die gesneuveld is:"
  no-latest-death: "Er is nog niemand gesneuveld!"
  latest-assist: "De laatste helpende hand:"
  no-latest-assist: "Er is nog niemand gul geweest!"
messages:
  death: "moet dokken!"
  not-dead-error: "Je bent niet dood, knurft..."
  assist-not-dead-error: "is niet dood, knurft..."
  assist-created: "Jouw hulp is gewaardeerd! 🔥"
  assist-received: "%player% heeft jou een assist gegeven van %percentage%% voor je volgende buyback!"
  buy-back-success: "Je bent terug gebracht!"
  penalty-given: "Speler %player% heeft een penalty van %amount% gekregen voor: %reason%!"
  grace-over: "%player% wordt niet langer beschermt en betaald nu de volle mep!"
  minimum-playtime-reached: "%player% heeft de minimale speeltijd behaalt! 🚀"
  debt: "Je zit momenteel €%amount% diep in de pot!"
piggy-bank-amounts:
  grace-period-death: 5
  normal-death: 10
timings:
  minimum-playtime: 90000
  grace-period: 7200
  death-grace-period: 600
worlds:
  # world_name:
  #   type: NORMAL / FLAT / LARGE_BIOMES / AMPLIFIED
  #   environment: NORMAL / NETHER / THE_END
  #   difficulty: PEACEFUL / EASY / NORMAL / HARD
  #   generate-structures: true / false
  #   daylight-cycle: true / false
  #   weather-cycle: true / false
  #   mob-spawning: true / false
  #   keep-inventory: true / false
  world_event_rps:
    type: "NORMAL"
    environment: "NETHER"
    difficulty: "HARD"
    generate-structures: false
    daylight-cycle: false
    weather-cycle: false
    mob-spawning: false
    keep-inventory: true