messages:
  death: "moet dokken!"
  not-dead-error: "Je bent niet dood, knurft..."
  assist-not-dead-error: "is niet dood, knurft..."
  assist-created: "Jouw hulp is gewaardeerd! 🔥"
  buy-back-success: "Je bent terug gebracht!"
  penalty-given: "Speler %player% heeft een penalty van %amount% gekregen voor: %reason%!"
  grace-over: "%player% wordt niet langer beschermt en betaald nu de volle mep!"
  minimum-playtime-reached: "%player% heeft de minimale speeltijd behaalt! 🚀"
  debt: "Je zit momenteel €%amount% diep in de pot!"
piggy-bank-amounts:
  grace-period-death: 5
  normal-death: 10
timings:
  minimum-playtime: 90000
  grace-period: 7200