messages:
  death: "moet dokken!"
  not-dead-error: "Je bent niet dood, knurft..."
  assist-not-dead-error: "is niet dood, knurft..."
  buy-back-success: "Je bent terug gebracht!"
piggy-bank-amounts:
  grace-period-death: 5
  normal-death: 10
  combat-log-penalty: 10
  cheat-penalty: 100