name: HardcoreSMPPlugin
version: '1.0-SNAPSHOT'
main: com.jouriroosjen.hardcoreSMPPlugin.HardcoreSMPPlugin
api-version: '1.21'
load: STARTUP
authors: [ JouriR ]
description: The custom plugin for our hardcore SMP with buy backs.
website: jouriroosjen.com
commands:
  buyback:
    description: "Buy yourself or another player back!"
    usage: "/buyback [<user>] [<percentage>]"
  confirm:
    description: "Confirm a pending confirmation."
    usage: "/confirm"
