name: HardcoreSMPPlugin
description: The custom plugin for our hardcore SMP with buy backs.
main: com.jouriroosjen.hardcoreSMPPlugin.HardcoreSMPPlugin
version: '0.2.0-BETA'
api-version: '1.21'
authors: [ JouriR ]
website: jouriroosjen.com
load: STARTUP
dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true
    DiscordSRV:
      load: BEFORE
      required: true
    floodgate:
      load: BEFORE
      required: true
commands:
  buyback:
    description: "Buy yourself or another player back!"
    usage: "/buyback [<user>] [<percentage>]"
  confirm:
    description: "Confirm a pending confirmation."
    usage: "/confirm"
  my-debt:
    description: "Show you're debt to the piggy bank."
    usage: "/my-debt"
  penalize:
    description: "Penalize a player when they cheated."
    usage: "/penalize <user> <amount> <reason>"
  place-hologram:
    description: "Places the specified hologram on your location."
    usage: "/place-hologram <PIGGY_BANK | LATEST_PENALTY | LATEST_DEATH | LATEST_ASSIST>"
